name: Scrape Events

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Puppeteer Core
      run: npm install puppeteer-core

    - name: Run scraper
      run: node scrape.js

    - name: Commit and push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add events.html
        git commit -m 'Update events.html'
        git push
